# Generated by Django 3.2.8 on 2021-11-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('idPunto', models.AutoField(primary_key=True, serialize=False)),
                ('idUser', models.PositiveIntegerField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('hora', models.DateField(auto_now=True)),
            ],
        ),
    ]
